### ISSUE TITLE
CORS error when attempting to source the script directly

### ISSUE THREAD

**Issue by AfroThundr3007730** [fightforthefuture/redalert-widget#7]
When attempting to source the script directly on a page, e.g.:
```html
<script type="text/javascript" integrity="sha384-mkxqkpp9upjUFsnbZ6AGdt1RXI5c+FaRIIczWA3NdvjgZvLRdWpC0zVdbFYDBGar"
    crossorigin="anonymous" async src="https://redalert.battleforthenet.com/widget.js"></script>
```
the following error is generated in the Firefox console:
>19:46:17.019 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://redalert.battleforthenet.com/widget.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 

and also on Chrome (with a more explanatory error message):
>15:55:57.945 Access to Script at 'https://redalert.battleforthenet.com/widget.js' from origin 'https://www.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.example.com' is therefore not allowed access.

This is because `https://redalert.fightforthefuture.org` is not serving an `Access-Control-Allow-Origin` response header when it receives a request with the `Origin` header set.

Notably, this issue does not occur when it is loaded through the normal BFTN widget. I suppose CORS isn't checked when the widget loads it.

-----

On another note, I had the same issue with my CSP blocking the injected CSS that I had on the original widget. See: fightforthefuture/battleforthenet-widget#106 for details. I applied the same solution here  by adding these rules to my site's  CSS directly:

```css
#RED_ALERT_WIDGET {
 position: fixed;
 right: 0;
 left: auto;
 bottom: 0px;
 width: 450px;
 height: 350px;
 z-index: 20000;
 -webkit-overflow-scrolling: touch;
 overflow: hidden;
 transition: width 200ms ease-in, height 200ms ease-in;
}

#RED_ALERT_WIDGET.RAW--maximized {
 width: 100%;
 height: 100%;
}

#RED_ALERT_WIDGET.RAW--closing {
 transform: scale(0);
 transform-origin: bottom right;
 opacity: 0;
 transition: transform 200ms ease-in, opacity 200ms ease-in;
}

#RED_ALERT_WIDGET iframe {
 width: 100%;
 height: 100%;
}
```

I still suggest that the necessary CSS rules be added as an external stylesheet that the widget can pull instead of putting the rules inline. That would make it play nicer with a CSP that doesn't allow `unsafe-inline` and also allow for SRI hashes to work properly.

And yes, I'm aware I can self host these and re-target the iframe, etc. I'm just suggesting how these improvements could be made upstream without having to go through that process.
